import type { MatchRule, ModelOption } from '@/types/image-to-video';

// Image to Video Models Configuration
export const ImageToVideoModels: Record<string, ModelOption> = {
  runway: {
    id: 'runway',
    name: 'Runway',
    platform: 'kie',
    model_brand: '',
    model_version: '',
    resolution: ['720p'],
    duration: [5, 8],
    aspect_ratio: ['16:9', '9:16', '1:1', '4:3', '3:4'],
    end_frame: false,
    match_rules: [
      {
        resolution: '1080p',
        allowed_durations: [5],
      },
    ],
    decrease_credits: [
      { resolution: '720p', duration: 5, cost_price: 0.06 },
      { resolution: '720p', duration: 8, cost_price: 0.15 }
    ],
    description: 'Multimodal, professional model',
    icon: '/imgs/models/runway.svg',
  },
  'soul-fuse-v1-6': {
    id: 'soul-fuse-v1-6',
    name: 'SoulFuse 1.6',
    platform: 'pollo',
    model_brand: 'pollo',
    model_version: 'pollo-v1-6',
    resolution: ['480p', '720p', '1080p'],
    duration: [5, 10],
    aspect_ratio: ['16:9', '9:16', '1:1'],
    end_frame: true,
    match_rules: [] as MatchRule[],
    decrease_credits: [
      { resolution: '480p', duration: 5, cost_price: 0.18 },
      { resolution: '480p', duration: 10, cost_price: 0.3 },
      { resolution: '720p', duration: 5, cost_price: 0.24 },
      { resolution: '720p', duration: 10, cost_price: 0.42 },
      { resolution: '1080p', duration: 5, cost_price: 0.54 },
      { resolution: '1080p', duration: 10, cost_price: 0.72 },
    ],
    description: 'Better, faster and cheaper',
    icon: '/imgs/models/soul-fuse.svg',
  },
  'veo3-fast': {
    id: 'veo3-fast',
    name: 'Google Veo 3 Fast',
    platform: 'apicore',
    model_brand: '',
    model_version: '',
    resolution: ['1080p'],
    duration: [8],
    aspect_ratio: ['16:9', '9:16'],
    end_frame: false,
    match_rules: [],
    decrease_credits: [{ resolution: '1080p', duration: 8, cost_price: 0.14 }],
    description: 'Veo 3 Fastmodel',
    icon: '/imgs/models/google-veo-3-fast.svg',
  },
  'video-01-live2d': {
    id: 'video-01-live2d',
    name: 'Hailuo Live2D',
    platform: 'pollo',
    model_brand: 'minimax',
    model_version: 'video-01-live2d',
    resolution: [] as string[],
    duration: [5] as number[],
    aspect_ratio: ['1:1'] as string[],
    match_rules: [] as MatchRule[],
    decrease_credits: [{ duration: 5, cost_price: 0.42 }],
    description: 'Good for 2D animation',
    icon: '/imgs/models/hailuo.svg',
  },
  'minimax-hailuo-02': {
    id: 'minimax-hailuo-02',
    name: 'Hailuo 02',
    platform: 'pollo',
    model_brand: 'minimax',
    model_version: 'minimax-hailuo-02',
    resolution: ['512p', '768p', '1080p'] as string[],
    duration: [6, 10] as number[],
    aspect_ratio: ['16:9', '9:16', '1:1'] as string[],
    match_rules: [] as MatchRule[],
    decrease_credits: [
      { resolution: '512p', duration: 6, cost_price: 0.12 },
      { resolution: '512p', duration: 10, cost_price: 0.24 },
      { resolution: '768p', duration: 6, cost_price: 0.3 },
      { resolution: '768p', duration: 10, cost_price: 0.72 },
      { resolution: '1080p', duration: 6, cost_price: 0.72 },
    ],
    description: 'Extreme physics simulations',
    icon: '/imgs/models/hailuo.svg',
  },
  'vidu-q1': {
    id: 'vidu-q1',
    name: 'Vidu Q1',
    platform: 'pollo',
    model_brand: 'vidu',
    model_version: 'vidu-q1',
    resolution: ['1080p'] as string[],
    duration: [5] as number[],
    aspect_ratio: ['16:9', '9:16'] as string[],
    end_frame: true,
    match_rules: [] as MatchRule[],
    decrease_credits: [{ resolution: '1080p', duration: 5, cost_price: 0.48 }],
    description: 'Precise control over video motion',
    icon: '/imgs/models/vidu.svg',
  },
  'vidu-v2-0': {
    id: 'vidu-v2-0',
    name: 'Vidu 2.0',
    platform: 'pollo',
    model_brand: 'vidu',
    model_version: 'vidu-v2-0',
    resolution: ['720p', '1080p'] as string[],
    duration: [4, 8] as number[],
    aspect_ratio: ['16:9', '9:16', '1:1'] as string[],
    end_frame: true,
    match_rules: [] as MatchRule[],
    decrease_credits: [
      { resolution: '720p', duration: 4, cost_price: 0.18 },
      { resolution: '720p', duration: 8, cost_price: 0.48 },
      { resolution: '1080p', duration: 4, cost_price: 0.48 },
    ],
    description: 'Enhanced quality and speed',
    icon: '/imgs/models/vidu.svg',
  },
  'pixverse-v5': {
    id: 'pixverse-v5',
    name: 'Pixverse V5',
    platform: 'pollo',
    model_brand: 'pixverse',
    model_version: 'pixverse-v5',
    resolution: ['360p', '540p', '720p', '1080p'] as string[],
    duration: [5, 8] as number[],
    aspect_ratio: ['16:9', '9:16', '1:1', '4:3'] as string[],
    end_frame: true,
    match_rules: [] as MatchRule[],
    decrease_credits: [
      { resolution: '360p', duration: 5, cost_price: 0.15 },
      { resolution: '540p', duration: 5, cost_price: 0.15 },
      { resolution: '720p', duration: 5, cost_price: 0.18 },
      { resolution: '1080p', duration: 5, cost_price: 0.36 },
      { resolution: '360p', duration: 8, cost_price: 0.3 },
      { resolution: '540p', duration: 8, cost_price: 0.3 },
      { resolution: '720p', duration: 8, cost_price: 0.36 },
    ],
    description: 'Smooth, expressive movements',
    icon: '/imgs/models/pixverse.svg',
  },
  'kling-v2-1': {
    id: 'kling-v2-1',
    name: 'Kling 2.1',
    platform: 'pollo',
    model_brand: 'kling-ai',
    model_version: 'kling-v2-1',
    resolution: [] as string[],
    duration: [5, 10],
    aspect_ratio: ['16:9', '9:16', '1:1'] as string[],
    match_rules: [] as MatchRule[],
    decrease_credits: [
      { duration: 5, cost_price: 0.21 },
      { duration: 10, cost_price: 0.42 },
    ],
    description: 'Enhanced visual realism and motion fluidity',
    icon: '/imgs/models/kling.svg',
  },
  'wan-v2-2-flash': {
    id: 'wan-v2-2-flash',
    name: 'Wan 2.2 Flash',
    platform: 'pollo',
    model_brand: 'wanx',
    model_version: 'wan-v2-2-flash',
    resolution: ['480p', '720p'],
    duration: [5],
    aspect_ratio: ['16:9', '9:16'],
    match_rules: [] as MatchRule[],
    decrease_credits: [
      { resolution: '480p', duration: 5, cost_price: 0.12 },
      { resolution: '720p', duration: 5, cost_price: 0.24 },
    ],
    description: 'Cinematic aesthetic videos',
    icon: '/imgs/models/wan.svg',
  },
  'wan-v2-2-plus': {
    id: 'wan-v2-2-plus',
    name: 'Wan 2.2 Plus',
    platform: 'pollo',
    model_brand: 'wanx',
    model_version: 'wan-v2-2-plus',
    resolution: ['480p', '1080p'],
    duration: [5],
    aspect_ratio: ['16:9', '9:16', '1:1'],
    match_rules: [] as MatchRule[],
    decrease_credits: [
      { resolution: '480p', duration: 5, cost_price: 0.24 },
      { resolution: '1080p', duration: 5, cost_price: 0.72 },
    ],
    description: 'Cinematic aesthetic videos',
    icon: '/imgs/models/wan.svg',
  },
};
